/*=========================================================
 E-COMMERCE SALES & CUSTOMER ANALYSIS 
 SQL EXPLORATORY DATA ANALYSIS
 =========================================================*/

-- 1. OVERALL BUSINESS PERFORMANCE 

--What is the total sales generated by the business?
SELECT SUM(sales_amount) total_sales
FROM gold.fact_sales

--How many items have been sold in total?
SELECT SUM(quantity) total_quantity
FROM gold.fact_sales

--What is the average selling price?
SELECT AVG(price) avg_price
FROM gold.fact_sales

--What is the total no. of orders?
SELECT COUNT(order_number) total_orders
FROM gold.fact_sales
--and actual total no. of unique orders?
SELECT COUNT(DISTINCT order_number) actual_total_orders
FROM gold.fact_sales

--What is the total no. of products?
SELECT COUNT(DISTINCT product_key) total_products
FROM gold.dim_products

--What is the total no. of customers?
SELECT COUNT(DISTINCT customer_key) total_customers
FROM gold.dim_customers

--How many customers have actually placed an order?
SELECT COUNT(DISTINCT customer_key) total_customers
FROM gold.fact_sales

-- 2. KEY METRICS REPORT

--What are the key business performance metrics?

SELECT 'Total Sales' measure_name, SUM(sales_amount) measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' measure_name, SUM(quantity) measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Aaverage Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total no.of Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total no.of Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total no.of Customers', COUNT(DISTINCT customer_key) FROM gold.dim_customers


-- 3. CUSTOMER ANALYSIS

--Which countries have the largest customer base?
SELECT 
country,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--What is the distribution of customers by gender?
SELECT 
gender,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--How much revenue has each customer generated?
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

--Which 10 customers have generated the highest revenue?
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


--Which 3 customers have placed the fewest orders?
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders 


-- 4. PRODUCT & CATEGORY ANALYSIS

--How many products are available in each category?
SELECT 
category,
COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average costs in each category?
SELECT 
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--What is the total revenue generated by each ctaegory?
SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Which 5 products subcategories generate the highest revenue?
SELECT TOP 5
p.subcategory,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC

--What are the 5 worst performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

--What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC







